import type { Metadata } from "next";
import "./globals.css";

// libraries
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

// components
import Footer from "../components/CoreComponents/Footer";

export const metadata: Metadata = {
  title: "Duhlicious",
  description: "Generated by create next app",
  icons: {
    icon: '/icons/duhliciousBgRemove3.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
          {children}
          <Footer />
        <ToastContainer />
        </body>
    </html>
  );
}
